### PR TITLE
should take large icon from mipmap

### PR DESCRIPTION
**Pull request by sksethi25**
we have our icons in mipmap, not in drawable anymore. so because of this even when u expand notification small icon was coming up

### CODE REVIEW

**Review by rampr — APPROVED** [review]

**Review by bijoshtj — APPROVED** [review]

**Comment by jishnu7** [comment]
notification icons doesn't have to be in mipmap, only app icons have to be there.

We keep icons in mipmap because, app launchers might show icons in different dpi than the device. but notification icons will always load the icons based on device dpi.

**Comment by rampr** [comment]
This is to pick the app icon when the notification is expanded. This change is not for notification icon.

**Comment by jishnu7** [comment]
got it.

**Comment by sksethi25** [comment]
@jishnu, we changed the reference to large icon that come up when you expand the notification. for one signal notification for our app and for all other apps we observed ,app icon was coming when you expand notifications. As we have our game icon only in mipmap,we pointed it to mipmap. if i am still missing something. please guide

**Comment by jishnu7** [comment]
@sksethi25 this change is correct. I thought this PR is to move notification icon (white one) to mipmap folder. my bad.

**Comment by sksethi25** [comment]
@jishnu7 thanks jishnu.

**Pull request merged**
